### ISSUE TITLE
Multi-GPU Processing

### ISSUE THREAD

**Issue by dbsxodud-11** [hsjang0/DPM-SNC#1]
Hi, I appreciate your hard work and it helps me really a lot.

I'm currently running the code on fully supervised setting with CORA dataset and GCN-based DPM in my server, which has 2 RTX 3090 NVIDIA GPU. I find that if there are more than two available GPUs, it automatically utilize parallelism. ([Here](https://github.com/hsjang0/DPM-GSP/blob/main/DPM-GSP-fully-supervised/utils/loader.py#L21))

However, I find error when using more than two GPUs, especially in adjacency list part. Adjacency list has a shape of (2, # number of edges) and when utilizing GPU parallelism, it splits adjacency list into two tensors where each has shape of (1, # number of edges), which is a not intended purpose and results in an error.

![image](https://github.com/hsjang0/DPM-GSP/assets/68262145/fd679324-aefc-4761-8686-3813a45b6100)

If I only use one GPU even I have more than that, code works fine. However, I want to utilize more than one GPU for fast training. Is there any possible way to solve this problem?

**Comment by hsjang0** [comment]
Thank you for your interest in our work! Since we revised the experiment and paper, the code base will also be updated soon :)

Furthermore, we only use one GPU in each experiment. However, if there is no problem with parallel processing, I will add it!
